CREATE TABLE [dbo].[AppointmentStudent] (
    [FACULTY_ID] VARCHAR (50) NOT NULL,
    [STUDENT_ID] VARCHAR (50) NOT NULL,
    [NAME]       VARCHAR (50) NOT NULL,
    [DEPARTMENT] VARCHAR (50) NOT NULL,
    [REQUEST]    VARCHAR (50) NOT NULL
);

GO
CREATE TABLE [dbo].[FACULTYDETAILS] (
    [ID]              VARCHAR (50) NOT NULL,
    [NAME]            VARCHAR (50) NOT NULL,
    [DEPARTMENT]      VARCHAR (50) NOT NULL,
    [CLASS_TIME]      VARCHAR (50) NOT NULL,
    [CONSULTING_TIME] VARCHAR (50) NOT NULL,
    [BUILDING_NAME]   VARCHAR (50) NOT NULL,
    [CUBICLE_NUMBER]  VARCHAR (50) NOT NULL,
    [PICTURE]         IMAGE        NULL
);

GO
CREATE TABLE [dbo].[LoginFac] (
    [USERNAME] VARCHAR (50) NOT NULL,
    [PASS]     VARCHAR (50) NOT NULL
);

GO
CREATE TABLE [dbo].[LoginStudent] (
    [USERNAME] VARCHAR (50) NOT NULL,
    [PASS]     VARCHAR (50) NOT NULL
);

GO
CREATE TABLE [dbo].[Response] (
    [FACULTY_ID]   VARCHAR (30) NOT NULL,
    [FACULTY_NAME] VARCHAR (30) NOT NULL,
    [DEPARTMENT]   VARCHAR (30) NOT NULL,
    [STUDENT_ID]   VARCHAR (30) NOT NULL,
    [REQUEST]      VARCHAR (30) NOT NULL
);

GO
CREATE TABLE [dbo].[STUDENTDETAILS] (
    [ID]         VARCHAR (50) NOT NULL,
    [NAME]       VARCHAR (50) NOT NULL,
    [DEPARTMENT] VARCHAR (50) NOT NULL,
    [PICTURE]    IMAGE        NULL
);

GO
